### ISSUE TITLE
[Bug]: invalid json: 404 page not found, err: invalid character 'p' after top-level value

### ISSUE THREAD

**Issue by emmmua** [Wsine/feishu2md#115]
### 问题描述

有没有人能够帮我下载试试链接：https://u1okvssixux.feishu.cn/docx/RKGhd5NKLoF65sxAin1cGjlznjg?from=from_copylink
完成日志
```log
feishu2md dl https://u1okvssixux.feishu.cn/docx/AS9hd9hn1oZ4nUxWJkqcuxrYnWQ
Captured document token: AS9hd9hn1oZ4nUxWJkqcuxrYnWQ
invalid json: 404 page not found, err: invalid character 'p' after top-level value

====================

Report the following if it is a bug

panic: invalid json: 404 page not found, err: invalid character 'p' after top-level value

goroutine 1 [running]:
github.com/Wsine/feishu2md/utils.CheckErr({0x11fb740, 0xc0001be060})
        /github/workspace/utils/common.go:19 +0x106
main.handleDownloadCommand({0xc00000e5c0?, 0xc000241c00?}, 0x16bd3e0)
        /github/workspace/cmd/download.go:68 +0x92d
main.main.func3(0xc00025e580)
        /github/workspace/cmd/main.go:69 +0xab
github.com/urfave/cli/v2.(*Command).Run(0xc00012d440, 0xc00025e3c0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/command.go:163 +0x583
github.com/urfave/cli/v2.(*App).RunContext(0xc000212680, {0x11fe370?, 0x17141a0}, {0xc000068080, 0x3, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:313 +0xaa5
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main()
        /github/workspace/cmd/main.go:76 +0x576
```

下载了一些图片
![image](https://github.com/Wsine/feishu2md/assets/78854689/0bb7b34b-3aa6-41e9-8a6b-e9de09c56424)

### 飞书文档链接

https://u1okvssixux.feishu.cn/docx/RKGhd5NKLoF65sxAin1cGjlznjg?from=from_copylink

### 期望的 markdown 格式

```markdown
无
```

**Comment by Wsine** [comment]
看日志是因为一些图片没有权限下载导致的，或许需要你自行排查一下是否有引用图片不属于自己的账号的。
