### ISSUE TITLE
下载文档出现invalid memory address or nil pointer dereference错误

### ISSUE THREAD

**Issue by KKCHANNEL-kk** [Wsine/feishu2md#3]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x977aa0]

goroutine 1 [running]:
github.com/chyroc/lark/larkext.(*Doc).content(0xc000271d08, {0xcfd030, 0xc00009e010})
        /home/jankin/.local/share/go/pkg/mod/github.com/chyroc/lark@v0.0.95/larkext/doc_impl.go:52 +0xa0
github.com/chyroc/lark/larkext.(*Doc).Content(...)
        /home/jankin/.local/share/go/pkg/mod/github.com/chyroc/lark@v0.0.95/larkext/doc.go:81
main.handleUrl({0xc0000a4050, 0xbaa7cd})
        /home/jankin/workspace/feishu2md/main.go:64 +0x34f
main.main.func1(0xc0001c5f00)
        /home/jankin/workspace/feishu2md/main.go:108 +0xcb
github.com/urfave/cli/v2.(*App).RunContext(0xc00022f040, {0xcfd030, 0xc00009e010}, {0xc0000963a0, 0x2, 0x2})
        /home/jankin/.local/share/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322 +0x7a8
github.com/urfave/cli/v2.(*App).Run(...)
        /home/jankin/.local/share/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main()
        /home/jankin/workspace/feishu2md/main.go:115 +0x145
```

**Comment by Wsine** [comment]
见 #2

**Comment by Wsine** [comment]
问题找到了。当提供的下载链接包含`#headers`后缀的时候，lark 库的内部处理会报错。

错误 URL：
```
https://oaztcemx3k.feishu.cn/docs/doccnrOvzeQ8BSnfsXj8jwJHC3c#gkgML5
```

正确 URL：
```
https://oaztcemx3k.feishu.cn/docs/doccnrOvzeQ8BSnfsXj8jwJHC3c
```

同时 [Release](https://github.com/Wsine/feishu2md/releases/tag/v0.1.2) 中提供了一个 v0.1.2 版本使用正则表达式提取 docToken，能同时handle上述两种情况

**Comment by KKCHANNEL-kk** [comment]
反而报`panic: unexpected end of JSON input`的问题了。
```
panic: unexpected end of JSON input

goroutine 1 [running]:
main.checkErr(...)
        /home/runner/work/feishu2md/feishu2md/utils.go:10
main.handleUrl({0xc000014280, 0x3d})
        /home/runner/work/feishu2md/feishu2md/main.go:71 +0x754
main.main.func1(0xc0002d2000)
        /home/runner/work/feishu2md/feishu2md/main.go:115 +0xcb
github.com/urfave/cli/v2.(*App).RunContext(0xc000251a00, {0xace2d0, 0xc00000a070}, {0xc0000503c0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322 +0x7a8
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main()
        /home/runner/work/feishu2md/feishu2md/main.go:122 +0x156
```
config.json 两种格式都已试过，均出现这个问题
![image](https://user-images.githubusercontent.com/67591719/170495573-a416afe8-ebd9-4533-b6d5-0ea49f1a0c61.png)

**Comment by Wsine** [comment]
这个问题希望到 #2 中去提问，让大家都能看到。我初步判断，先删掉第10行的空行再运行看看。golang 反序列化的时候似乎不支持这个情况。
